# Generated by Django 4.2.13 on 2024-06-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(default='My Blog', max_length=200)),
                ('blog_subtitle', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
