# Generated by Django 4.2.13 on 2024-06-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='posts_per_page',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
