# Generated by Django 4.2.13 on 2024-06-04 08:18

from django.db import migrations, models
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_sitesettings_posts_per_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', django_ckeditor_5.fields.CKEditor5Field()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
