# Generated by Django 4.2.13 on 2024-06-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_time']},
        ),
    ]
